acme_viajes:
    resource: "@AcmeViajesBundle/Resources/config/routing/main.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_viajes_usuario:
    resource: "@AcmeViajesBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario